### ISSUE TITLE
Scraping doesn't work at all

### ISSUE THREAD

**Issue by OmgImAlexis** [Pappa/TorrentJS#1]
I found a snippet of your scraping code on Stackoverflow and I've been trying to get it working but I've been having trouble. When I run this app and try going to the `/scrape?info_hashes=HASH_HERE` page it never loads and the scrape doesn't seem to happen.

```
➜  TorrentJS git:(master) node server.js
Listening on port 2000
server listening 0.0.0.0:49714
scraping
```

**Comment by Pappa** [comment]
Sorry for the delay in responding. I noticed some time ago that this was no longer working, but I haven't had chance to look into it as yet.

**Comment by OmgImAlexis** [comment]
@Pappa all's good. :+1:
